kind: Deployment
apiVersion: apps/v1
metadata:
  name: flask-deploy
  namespace: demo
  labels:
    app: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: sumilkatiyar/pythonflask:flaskappv1
          ports:
            - containerPort: 80
