kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-app-deployment
  namespace: demo
  labels:
    app: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: us-central1-docker.pkg.dev/user-rkxfhglrrqjs/my-docker-repo/flask
          ports:
            - containerPort: 80
