apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: demo
spec:
  type: LoadBalancer
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

